web: python manage.py makemigrations && \
      python manage.py migrate && \
      python manage.py collectstatic --noinput && \
      gunicorn image_search.wsgi:application --bind 0.0.0.0:$PORT --log-file - --timeout 120
